version: "3.9"
services: 
  # Frontend
  app:
    build: ./frontend
    ports: 
      - 8080:80
    networks:
      app-network:
        ipv4_address: "10.88.0.21"
      
  # Backend
  server:
    build: ./backend
    ports: 
      - 8000:8000
    networks:
      app-network:
        #bind to apache proxy pass
        ipv4_address: "10.88.0.11"
    hostname: backend
  # Weather
  weather:
    build: ./weather-service
    ports:
      - 8081:8081
    networks:
      app-network:
        ipv4_address: "10.88.0.31"
  # Window
  window:
    build: ./window-service
    ports:
      - 8082:8082
    networks:
      app-network:
        ipv4_address: "10.88.0.41"
    hostname: window-service
  # Door
  door:
    build: ./door-service
    ports:
      - 8083:8083
    networks:
      app-network:
        ipv4_address: "10.88.0.51"
    hostname: door-service
  # Heat Pump
  heat-pump:
    build: ./heat-pump-service
    ports:
      - 8084:8084
    networks:
      app-network:
        ipv4_address: "10.88.0.61"
  # Thermometer
  thermometer:
    build: ./thermometer-service
    ports:
      - 8085:8085
    networks:
      app-network:
        ipv4_address: "10.88.0.71"
  # Actuator
  actuator:
    build: ./actuator
    ports:
      - 8086:8086
    networks:
      app-network:
        ipv4_address: "10.88.0.81"
    hostname: actuator

networks:
  app-network:    
      name: app-network
      driver: bridge
      ipam:
        config:
          - subnet: "10.88.0.0/16"
